stages:
    - test

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - pip3 install coverage
        - coverage erase
        - coverage run -a --source=app --branch -m unittest test/calculator_blackbox_unittest.py
        - coverage run -a --source=app --branch -m unittest test/calculator_solarapi_unittest.py
        - coverage run -a --source=app --branch -m unittest test/state_holiday_unittest.py
        - coverage run -a --source=app --branch -m unittest test/requirement_1_whitebox_unittest.py
        - coverage run -a --source=app --branch -m unittest test/future_solar_energy_testing.py
        - coverage run -a --source=app --branch -m unittest test/validation_unittest.py
        - coverage run -a --source=app --branch -m unittest test/requirement_2_whitebox_unittest.py
        - coverage report -m
        - coverage html -d coverage_reports
    artifacts:
        paths:
            - coverage_reports/
